#!/usr/bin/perl

# 39.7022828926,-104.98279701: 0.10 124298330 22.7575 unknown 39.7022828947636,-104.982797383219

$pi = 4 * atan2(1, 1);
$foot = .00000274;

while (<>) {
	chomp;
	($where, $dist, $way, $along, $oneway, $len) = split(/ /);
	($lat, $lon) = split(/,/, $where);

	$oneway{$way} = $oneway;
	$len{$way} = $len;

	if ($way eq $oway) {
		$latd = $lat - $olat;
		$lond = ($lon - $olon) * cos($lat * $pi / 180);
		$d = sqrt($latd * $latd + $lond * $lond);

		if ($d > 75 * $foot) {
			if ($along > $oalong) {
				$tally{$way} += $d / $foot;
				$count{$way} += $d / $foot;
			} elsif ($along < $oalong) {
				$tally{$way} -= $d / $foot;
				$count{$way} += $d / $foot;
			}

			$traversed{$way} += $d / $foot;
		} else {
			# retain old lat/lon/along for next check
			next;
		}
	}

	$oway = $way;
	$oalong = $along;
	$olat = $lat;
	$olon = $lon;
}

for $way (sort { $traversed{$b} / $len{$b} <=> $traversed{$a} / $len{$a} } keys(%count)) {

	next if $traversed{$way} / $len{$way} < 10;

	if ($oneway{$way} eq "yes" && $tally{$way} / $count{$way} * 100 < 88) {
		print "wrong ";
	} elsif ($oneway{$way} ne "yes" && $tally{$way} / $count{$way} * 100 > 88) {
		print "wrong ";
	} elsif ($oneway{$way} ne "-1" && $tally{$way} / $count{$way} * 100 < -88) {
		print "wrong ";
	} else {
		print "ok    ";
	}

	printf("%.4f ", $tally{$way} / $count{$way} * 100);
	print "$oneway{$way} $way ";

	printf("%.3f ", $traversed{$way} / $len{$way});
	printf("%d %d\n", $tally{$way}, $count{$way});
}
